ALTER TABLE public.site_about
  ADD COLUMN IF NOT EXISTS stat_1_subtitle text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_1_line1 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_1_line2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_1_line3 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_2_subtitle text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_2_line1 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_2_line2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_2_line3 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_3_subtitle text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_3_line1 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_3_line2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stat_3_line3 text NOT NULL DEFAULT '';